name: Feature Request
description: Request a new feature
title: '[FR] '
body:
  - type: markdown
    attributes:
      value: |
        # Only English
  - type: textarea
    attributes:
      label: Feature description
      description: Please provide a clear and concise description of what you want to happen and what problem will this solve.
    validations:
      required: true
