name: Publish to WinGet
on:
  release:
    types: [released]

env:
    IDENTIFIER: ${{ endsWith(github.event.release.tag_name, 'dev') && 'Hiddify.Next.Beta' || 'Hiddify.Next' }}

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: ${{ env.IDENTIFIER }}
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}